// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using btsosecim.Data;

#nullable disable

namespace btsosecim.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260905155935_BorcAlaniEkle")]
    partial class BorcAlaniEkle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("btsosecim.Models.Firma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BorcMiktari")
                        .HasColumnType("numeric");

                    b.Property<string>("EvrakDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KomiteNo")
                        .HasColumnType("integer");

                    b.Property<bool>("SecimGeldiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UyeDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YemekAramaDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("YemekFiiliKatilim")
                        .HasColumnType("boolean");

                    b.Property<string>("YemekTeyitDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YetkiliIsim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YetkiliTelefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zimmet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KomiteNo");

                    b.HasIndex("SicilNo")
                        .IsUnique();

                    b.HasIndex("Zimmet");

                    b.ToTable("Firmalar", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
